CREATE DATABASE mytest;

CREATE TABLE t_user(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL ,
  age INT NOT NULL,
  password VARCHAR(50) NOT NULL ,
  phone VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8;